### ISSUE TITLE
License: MIT?

### ISSUE THREAD

**Issue by aurodev** [DavidArno/Ash.NET#3]
Would like to use as a base for my ECS if the license is MIT.

Thanks in advance.
Good luck with your other projects!

**Comment by DavidArno** [comment]
Hi,
I didn't add a licence file as it is a derivative work of the [original Ash framework by Richard Lord](https://github.com/richardlord/Ash), and thus is covered by its licence, which is MIT. I can certainly add an explicit MIT licence if you'd prefer. 

However, before using this as the base for any project you might undertake, do also check out [Unity Ash, by Mike Cann](https://github.com/mikecann/Unity-Ash), which is another C# based port of Ash. Mike has put far more work into that port than I ever did with this one. Again, that's an MIT licence, so take you pick and have fun.
